language: r
dist: trusty
sudo: true
os:
  - linux
cache:
  directories:
    - $HOME/.cache # hdf5
    - $HOME/R/Library
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_030782d20dd6_key -iv $encrypted_030782d20dd6_iv -in credentials.enc -out credentials -d
- source credentials
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
install:
- update_docker
- install_hdf5
- install_cran devtools
- install_github_withdeps dynverse/dynwrap
- install_github_withdeps dynverse/dyntoy
- install_github_withdeps dynverse/dyneval
script:
- source version
- build_docker
- test_docker
after_success:
- push_docker
jobs:
  include:
    - stage: cache
      script:
        - echo Don't build/test docker since this is a cache warmup
      after_success:
        - echo Don't push docker since this is a cache warmup
    - stage: build
